version: '3.8'

services:
  mysql_container:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./MySQL/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - etl_network

  etl_script:
    build:
      context: ./ETL
    container_name: etl_script_container
    volumes:
      - ./data:/data               # Mount data directory
      - ./ETL:/app                 # Mount ETL directory
    depends_on:
      - mysql_container
    networks:
      - etl_network

networks:
  etl_network:
    driver: bridge
